/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("org.catplayer.netty.coroutines.common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

dependencies {
    // https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
    implementation("ch.qos.logback:logback-classic:1.5.6")

}

application {
    applicationDefaultJvmArgs = listOf(
        "--add-opens",
        "java.base/jdk.internal.misc=ALL-UNNAMED",
        "--add-opens",
        "java.base/java.lang=ALL-UNNAMED",
        "-Dio.netty.tryReflectionSetAccessible=true",
        "--add-opens",
        "java.base/java.nio=ALL-UNNAMED"
    )
}
